keys:
  - &bw_age_key age15jkdns7a6m5j457ew0kr0lwznt5nje9fn76n7vy7c7u80k5ny5askks206
  - &bw_ssh_key age1znjzjvdpdjuted8yrrwuyhs74a8ufcrtqsy7pwfuzx53l6nr2v0s7dl6hw
creation_rules:
  - path_regex: secrets/unraid-services.yaml$
    key_groups:
      - age:
          - *bw_age_key
          - *bw_ssh_key
